blank_issues_enabled: false
contact_links:
  - name: Spoolman Community Discussion
    url: https://github.com/Donkie/Spoolman/discussions
    about: Please use the main Spoolman discussions for general support or questions about Spoolman itself.
